from pathlib import Path
import runpy

ROOT = Path("AWS-Enterprise-Architecture-Handbook")
SOURCE = ROOT / "docs" / "diagrams" / "aws-diagrams"
OUTPUT = ROOT / "docs" / "diagrams" / "rendered"
GALLERY = ROOT / "docs" / "diagrams" / "README.md"
REFERENCE_DOCS = ROOT / "docs" / "reference-architectures"

OUTPUT.mkdir(parents=True, exist_ok=True)

sources = sorted(SOURCE.glob("*.py"))
if not sources:
    raise SystemExit(f"No Python AWS diagram sources found in {SOURCE}")

# Every reference-architecture article must have a same-name architecture-as-code source.
reference_articles = sorted(REFERENCE_DOCS.glob("*.md"))
source_stems = {path.stem for path in sources}
missing_sources = [article for article in reference_articles if article.stem not in source_stems]
if missing_sources:
    details = "\n".join(f" - {path}" for path in missing_sources)
    raise SystemExit(f"Reference architectures missing Python diagram sources:\n{details}")

# Remove stale generated files so validation cannot pass on obsolete assets.
for pattern in ("*.png", "*.svg"):
    for old in OUTPUT.glob(pattern):
        old.unlink()

for source in sources:
    print(f"Rendering {source}")
    runpy.run_path(str(source), run_name="__main__")

rendered = sorted(OUTPUT.glob("*.png"))
rendered_stems = {path.stem for path in rendered}
if rendered_stems != source_stems:
    missing = sorted(source_stems - rendered_stems)
    extra = sorted(rendered_stems - source_stems)
    raise SystemExit(f"Rendered/source mismatch. Missing={missing}; Extra={extra}")

workflow_schematic = [
    "## How GitHub Actions Builds the Diagrams",
    "",
    "```mermaid",
    "flowchart TD",
    "    A[Push to master or manual workflow_dispatch] --> B[actions/checkout@v4]",
    "    B --> C[actions/setup-python@v5 / Python 3.12]",
    "    C --> D[Install Graphviz + diagrams 0.24.4]",
    "    D --> E[Scan docs/diagrams/aws-diagrams/*.py]",
    "    E --> F[Validate every Python and AWS icon import]",
    "    F --> G[Compare docs/reference-architectures/*.md to Python source stems]",
    "    G --> H[Run scripts/render_aws_diagrams.py]",
    "    H --> I[Execute each architecture source with runpy]",
    "    I --> J[Graphviz renders AWS-icon PNG assets]",
    "    J --> K[Write docs/diagrams/rendered/*.png]",
    "    K --> L[Regenerate docs/diagrams/README.md gallery]",
    "    L --> M[Validate source count, PNG count, gallery and coverage]",
    "    M --> N[github-actions bot commits generated diagrams and gallery]",
    "```",
    "",
    "### Assets and Commands",
    "",
    "| Stage | Input or command | Output |",
    "|---|---|---|",
    "| Architecture narratives | `docs/reference-architectures/*.md` | Coverage requirements |",
    "| Editable diagram definitions | `docs/diagrams/aws-diagrams/*.py` | AWS architecture-as-code |",
    "| Import validation | Python AST + `importlib.import_module(...)` | Verified icon/module compatibility |",
    "| Renderer | `python AWS-Enterprise-Architecture-Handbook/scripts/render_aws_diagrams.py` | Executes every diagram source |",
    "| Graph engine | Graphviz invoked by Python `diagrams` | Professional AWS-icon topology |",
    "| Rendered assets | Generated from each `.py` source | `docs/diagrams/rendered/*.png` |",
    "| Gallery | Generated by the renderer | `docs/diagrams/README.md` |",
    "| Publication | `git add`, `git commit`, `git push` in Actions | Generated assets committed to `master` |",
    "",
]

lines = [
    "# AWS Architecture Diagram Gallery",
    "",
    "These diagrams are generated as architecture-as-code with the Python `diagrams` library and Graphviz, using AWS service icons and professional account, Region, VPC, subnet, security, data, and application boundaries.",
    "",
    "> PNG previews are the primary presentation format. Python source files under `aws-diagrams/` are the editable architecture-as-code definitions.",
    "",
    *workflow_schematic,
]

articles_by_stem = {path.stem: path for path in reference_articles}
for image in rendered:
    title = image.stem.replace("-", " ").title()
    source = SOURCE / f"{image.stem}.py"
    lines += [
        f"## {title}",
        "",
        f"![{title}](rendered/{image.name})",
        "",
        f"[Editable Python diagram source](aws-diagrams/{source.name})",
    ]
    article = articles_by_stem.get(image.stem)
    if article:
        lines.append(f" · [Reference architecture](../reference-architectures/{article.name})")
    lines.append("")

GALLERY.write_text("\n".join(lines), encoding="utf-8")
print(f"Rendered {len(rendered)} AWS architecture diagrams into {OUTPUT}")
print(f"Reference architecture coverage: {len(reference_articles)}/{len(reference_articles)}")
